const SERVER_ENDPOINT = "http://10.0.0.163:8080/";
const CREATE_PROJECT_ENDPOINT = `${SERVER_ENDPOINT}project`;
const ARCHIVE_PROJECT_ENDPOINT = `${SERVER_ENDPOINT}project/archive`;
const GET_PROJECTS_ENDPOINT = `${SERVER_ENDPOINT}projects`;
const GET_COMPLETE_PROJECT_ENDPOINT = `${SERVER_ENDPOINT}project`;

export {
    SERVER_ENDPOINT,
    CREATE_PROJECT_ENDPOINT,
    ARCHIVE_PROJECT_ENDPOINT,
    GET_PROJECTS_ENDPOINT,
    GET_COMPLETE_PROJECT_ENDPOINT,
}