const SERVER_ENDPOINT = "http://10.0.0.163:8080/";
const CREATE_PROJECT_ENDPOINT = `${SERVER_ENDPOINT}project`;
const GET_PROJECTS_ENDPOINT = `${SERVER_ENDPOINT}projects`;

export {
    SERVER_ENDPOINT,
    CREATE_PROJECT_ENDPOINT,
    GET_PROJECTS_ENDPOINT,
}