export const PROJECT_NAME_TEXT = 'Project Name';
export const PROJECT_DESCRIPTION_TEXT = 'Project Description';
export const CREATE_PROJECT_BUTTON_TEXT = 'Create Project';
export const CREATE_BUTTON_TEXT = 'Create';
export const ARCHIVE_BUTTON_TEXT = 'Archive';
export const CREATE_TASK_BUTTON_TEXT = 'Create Task';
export const GENERATE_TASKS_SUBTASKS_BUTTON_TEXT = 'Generate Tasks & SubTasks';
export const REGENERATE_TASKS_SUBTASKS_BUTTON_TEXT = 'Regenerate Tasks & SubTasks';
export const SUMMARIZE_BUTTON_TEXT = 'Summarize';